### ISSUE TITLE
Train a classifier for good and bad aspects

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/comparely#3]
Use this dataset (https://docs.google.com/spreadsheets/d/13KDLkMlRGYIXAynF7TBabsqGac-H5EgzfHagB-Nd2vk/edit#gid=1722006798) which was FIRST cleaned in #2 and predict GOOD/BAD labels.

**Comment by varvara-l** [comment]
Done, the results are here: https://docs.google.com/spreadsheets/d/1rMIdEk0FcBN9thCaP3bKc2lbzMQNJ7428XNJT7ZS3No/edit?usp=sharing, in the "Aspect classifier" tab.
